### ISSUE TITLE
no requirements file

### ISSUE THREAD

**Issue by mcoughlin** [nmiranda/SNGuess#1]
There is a snguess.yml for a (Linux?) environment in notebooks, but no requirements file which makes installation on any other system very challenging. The repo should have a sensible requirements file enabling the repo to be installed with pip or poetry or similar.

**Comment by mcoughlin** [comment]
On a related note, from ampel.contrib.hu.t2.T2BrightSNProb import T2BrightSNProb
is not obvious where it is installable on pypi

**Comment by nmiranda** [comment]
SNGuess can be now installed from pypi via pip.
